[package]
name = "argus-scanner"
version = "0.3.0"
edition = "2024"
description = "Local security scanner and defensive OSINT toolkit for repos, hosts, and public records"
license-file = "LICENSE"
repository = "https://github.com/Quad4-Software/argus"
homepage = "https://quad4-software.github.io/argus/"
readme = "README.md"
keywords = ["supply-chain", "security", "secrets", "osint", "scanner"]
categories = ["command-line-utilities", "development-tools", "security"]
exclude = ["json"]

[[bin]]
name = "argus"
path = "src/main.rs"

[target.'cfg(target_os = "linux")'.dependencies]
landlock = "0.4.7"

[dependencies]
clap = { version = "4.6", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "1.1"
regex = "1.13"
sha2 = "0.11"
ureq = "3.4"
clap_complete = "4.6"
yara-x = { version = "1", optional = true }
yaml-rust2 = "0.13.0"
rusqlite = { version = "0.40", features = ["bundled"] }
hmac = "0.13"
ed25519-dalek = { version = "3", features = ["pkcs8"] }
getrandom = "0.3"
maxminddb = { version = "0.32.0", features = ["mmap"] }
flate2 = "1.1.10"
postgres = { version = "0.19.14", optional = true }
ignore = "0.4"
aho-corasick = "1.1"
regex-syntax = "0.8"
tree-sitter = { version = "0.25", optional = true }
streaming-iterator = { version = "0.1", optional = true }
tree-sitter-python = { version = "0.25", optional = true }
tree-sitter-javascript = { version = "0.25", optional = true }
tree-sitter-typescript = { version = "0.23", optional = true }
tree-sitter-go = { version = "0.25", optional = true }
tree-sitter-rust = { version = "0.24", optional = true }
p256 = "0.13.2"
x509-parser = "0.18.1"
base64 = "0.23.1"
p384 = "0.14.0"
rsa = { version = "0.9.10", features = ["sha2"] }

[features]
default = ["yara", "ast"]
ast = [
    "dep:tree-sitter",
    "dep:streaming-iterator",
    "dep:tree-sitter-python",
    "dep:tree-sitter-javascript",
    "dep:tree-sitter-typescript",
    "dep:tree-sitter-go",
    "dep:tree-sitter-rust",
]
yara = ["dep:yara-x"]
postgres = ["dep:postgres"]

[profile.release]
lto = true
strip = true

[dev-dependencies]
sha2 = "0.11"
